version: "2"
services:
  # api:
  #   container_name: 'API'
  #   build: ./API
  #   command: node ace serve --watch
  #   ports:
  #     - '3333:3333'
  #   depends_on:
  #     - mysql
  #     - kafka
  
  # ms_emails: 
  #   container_name: 'MS-EMAILS'
  #   build: ./MS-EMAILS
  #   command: npm run dev
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - kafka
    
  # ms_client_review:
  #   container_name: 'MS-CLIENT-REVIEW'
  #   build: ./MS-CLIENT-REVIEW
  #   command: npm run dev
  #   ports:
  #     - '3002:3002'
  #   depends_on:
  #     - mysql
  #     - kafka

  mysql: 
    container_name: 'MYSQL'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_lubycash
      - TZ=America/Sao_Paulo

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
